BOARD_TAG    = nano # Here goes your board type, e.g. : uno
BOARD_SUB = atmega328old
ARDUINO_PORT = /dev/ttyUSB0 # Change to your own tty interface

ARDUINO_LIBS = # The libs needed by your sketchbook, examples are : Wire Wire/utility Ethernet...

include Arduino.mk # This is where arduino-mk installed
AVRDUDE_CONF = /usr/share/arduino/hardware/tools/avrdude.conf
